cloudapp/cloudapp/urls.py
from user.views import logout, register, login
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^exam/', include('exam.urls', namespace='exam')),
    url(r'^main/', include('user.urls', namespace='user')),
    url(r'^$', logout, name="logout"),
    url(r'^register/$', register, name="register"),
    url(r'^login/$', login, name="login")
]

cloudapp/exam/urls.py
from django.conf.urls import url, include
from django.urls import path
from .views import exam_create, exam_index, exam_delete, exam_detail, exam_scores,exam_answer

app_name = "exam"
urlpatterns = [
    url(r'^create/$', exam_create, name="create"),
    url(r'^index/$', exam_index, name="index"),
    url(r'^(?P<exam_id>\w+)/answers/$', exam_answer, name="answers"),
    url(r'^(?P<exam_id>\w+)/delete/$', exam_delete, name="delete"),
    url(r'^(?P<exam_id>\w+)/scores/$', exam_scores, name="scores"),
    url(r'^(?P<exam_id>\w+)/', exam_detail, name="detail"),

]

cloudapp/user/urls.py
from django.conf.urls import url, include
from .views import register, student_main, instructor_main
from django.conf.urls import url, include

app_name = "user"
urlpatterns = [
    url(r'^student/$', student_main, name='student'),
    url(r'^instructor/$', instructor_main, name='instructor'),
    url(r'^student/exam/', include('exam.urls')),
    url(r'^instructor/exam/', include('exam.urls')),

]

cloudapp/main/models.py
from django.db import models

# Create your models here.

cloudapp/main/views.py
from django.shortcuts import render

cloudapp/templates/base.html
{% load static %}

<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
        {% block title %}
            Quon
         {% endblock %}

    </title>
    {% block date %}

    {% endblock %}

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <!-- CSS here   -->
    <link rel="stylesheet" href="{% static 'css/solvee.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/progressbar_barfiller.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animated-headline.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>

<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src=" {% static 'img/logo/loder.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
        <div class="header-area header-transparent">
            <div class="main-header ">
                <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-2 col-lg-2">
                                <div class="logo">
                                    {% if request.session.logged %}
                                    {% if request.session.organizer %}
                                    <a href="{% url 'user:instructor' %}"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
                                    {% else %}
                                    <a href="{% url 'user:student' %}"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
                                    {% endif %}
                                    {% else %}
                                    <a href="{% url 'logout' %}"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-xl-10 col-lg-10">
                                <div class="menu-wrapper d-flex align-items-center justify-content-end">
                                    <!-- Main-menu -->
                                    <div class="main-menu d-none d-lg-block">
                                        <nav>
                                            <ul id="navigation">
                                                {% if request.session.organizer %}
                                                <a href="{% url 'user:instructor' %}">Home</a>

                                                {% else %}
                                                    <a href="{% url 'user:student' %}">Home</a>
                                                {% endif %}
                                                <!-- Button -->
                                                {% if request.session.logged %}
                                                <li><a href="#">Welcome</a></li>
                                                <li><a href="#">{{request.session.name}}</a></li>
                                                <li class="button-header"><a href="{% url 'logout' %}" class="btn btn3">Log out</a></li>
                                                {% else %}
                                                {%block join %}<li class="button-header margin-left "><a href="../../../../register" class="btn">Join</a></li>{%endblock%}
                                                {%block login %}<li class="button-header"><a href="../../../../login" class="btn btn3">Log in</a></li>{%endblock%}
                                                {% endif %}
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>



        {% block body %}

         {% endblock %}


    <footer>
     <div class="footer-wrappper footer-bg">
        <!-- Footer Start-->
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-xl-4 col-lg-5 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">
                                <!-- logo -->
                                <div class="footer-logo mb-25">
                                    <a href="index.html"><img src="{% static 'img/logo/logo2_footer.png' %}" alt=""></a>
                                </div>
                                <div class="footer-tittle">
                                    <div class="footer-pera">
                                        <p>Online Quiz System
                                          Schedule your exams quickly.</p>

                                    </div>
                                </div>
                                <!-- social --><div class="footer-social">
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- footer-bottom area -->
        <div class="footer-bottom-area">
            <div class="container">
                <div class="footer-border">
                    <div class="row d-flex align-items-center">
                        <div class="col-xl-12 ">
                            <div class="footer-copy-right text-center">
                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved</a>
                                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          <!-- Footer End-->
      </div>
  </footer>
  <!-- Scroll Up -->
  <div id="back-top" >
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>

<!-- JS here -->
<script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<!-- One Page, Animated-HeadLin -->
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/animated.headline.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

<!-- Date Picker -->
<script src="{% static 'js/gijgo.min.js' %}"></script>
<!-- Nice-select, sticky -->
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<!-- Progress -->
<script src="{% static 'js/jquery.barfiller.js' %}"></script>

<!-- counter , waypoint,Hover Direction -->
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/hover-direction-snake.min.js' %}"></script>

<!-- contact js -->
<script src="{% static 'js/contact.js' %}"></script>
<script src="{% static 'js/jquery.form.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

cloudapp/templates/deneme.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  Anasayfa  {{ isim }}
</body>
</html>

cloudapp/templates/instructor.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
            O | Instructor
         {% endblock %}


{% block body %}
    <main>
        <!--? slider Area Start-->
        <section class="slider-area slider-area2">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height2">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-8 col-lg-11 col-md-12">
                                <div class="hero__caption hero__caption2">
                                    <h1 data-animation="bounceIn" data-delay="0.2s">Instructor System</h1>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--? Blog Area Start-->

        <section class="blog_area section-padding">
            <div class="container">
                <div class="row">

                {% if message %}



                     {% if warning %}
                          <div class="col-lg-12 mb-12 mb-lg-12">
                               <div class="alert alert-danger" role="alert">
                                     {{ message }}
                               </div>
                          </div>
                     {% else %}
                          <div class="col-lg-12 mb-12 mb-lg-12">
                                <div class="alert alert-success" role="alert">
                                      {{ message }}
                                </div>
                          </div>
                     {% endif %}


                {% endif %}

                    <br><br>
                    <div class="col-lg-12 mb-12 mb-lg-12">
                        <div class="blog_left_sidebar">

                            {% for exam in exams %}
                            <article class="blog_item">

                                <div class="blog_details">
                                    <a class="d-inline-block" href="#">
                                        <h2 class="blog-head" style="color: #2d2d2d;">{{ exam.name }}</h2>
                                    </a>

                                        <h5 class="blog-head" style="color: #2d2d2d;">{{ exam.org_name }}</h5>

                                    <p>Dont Cheat | Lecture</p>
                                    <div class="d-inline-block">
                                        <a href="{% url 'exam:detail' exam_id=exam.id %}" class="genric-btn info circle arrow">Detail<span class="lnr lnr-arrow-right"></span></a>
                                        <a href="{% url 'exam:scores' exam_id=exam.id %}" class="genric-btn success circle arrow">Results<span class="lnr lnr-arrow-right"></span></a>
                                        <a href="{% url 'exam:delete' exam_id=exam.id %}" class="genric-btn danger circle arrow">Delete<span class="lnr lnr-arrow-right"></span></a>
                                    </div>
                                    </div>


                            </article>
                            {% endfor%}
                            <div class="col-xl-12 col-lg-12 col-md-12 ">
                                <div class="d-flex justify-content-center ">
                                    <li class="button-header margin-right ">
                                        <a id="createQuestion"class="btn  btn-success"  href="{% url 'exam:create' %}" type="button" value="Create Exam">Create Exam</a>
                                    </li>
                                </div>
                             </div>
                            <br><br>
                            <nav class="blog-pagination justify-content-center d-flex">
                                <ul class="pagination">
                                    <li class="page-item">
                                        <a href="#" class="page-link" aria-label="Previous">
                                            <i class="ti-angle-left"></i>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="#" class="page-link">1</a>
                                    </li>
                                    <li class="page-item active">
                                        <a href="#" class="page-link">2</a>
                                    </li>
                                    <li class="page-item">
                                        <a href="#" class="page-link" aria-label="Next">
                                            <i class="ti-angle-right"></i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>


                </div>
            </div>
        </section>
        <!-- Blog Area End -->
    </main>
{% endblock%}

cloudapp/templates/login.html
{% load static %}

<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> App landing</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

	<!-- CSS here -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/progressbar_barfiller.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animated-headline.css' %}">
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'css/slick.css' %}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'img/logo/loder.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start-->

    <main class="login-body" data-vide-bg="{% static 'img/login-bg.mp4' %}">
        <!-- Login Admin -->
        <form class="form-default" action="" method="POST">

            <div class="login-form">
                <!-- logo-login -->
                <div class="logo-login">
                    <a href="index.html"><img src="{% static 'img/logo/loder.png' %}" alt=""></a>
                </div>
                <h2>Login Here</h2>
                {% if  msg%}
                <div class="form-input">
                         <div class="alert alert-success" role="alert">
                                                       {{ msg }}
                         </div>
                </div>
                {% endif %}
                <div class="form-input">
                    <label for="name">Email</label>
                    <input  type="email" name="email" placeholder="Email">
                </div>
                <div class="form-input">
                    <label for="name">Password</label>
                    <input type="password" name="password" placeholder="Password">
                </div>
                <div class="form-input pt-30">
                    <input type="submit" name="submit" value="login">
                </div>

                <!-- Forget Password -->
                <a href="#" class="forget">Forget Password</a>
                <!-- Forget Password -->
                <a href="{% url 'register' %}" class="registration">Registration</a>
            </div>
        </form>
        <!-- /end login form -->
    </main>

    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>

    <!-- Video bg -->
    <script src="{% static 'js/jquery.vide.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/animated.headline.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

    <!-- Date Picker -->
    <script src="{% static 'js/gijgo.min.js' %}"></script>
    <!-- Nice-select, sticky -->
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <!-- Progress -->
    <script src="{% static 'js/jquery.barfiller.js' %}"></script>

    <!-- counter , waypoint,Hover Direction -->
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/hover-direction-snake.min.js' %}"></script>

    <!-- contact js -->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    </body>
</html>

cloudapp/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
            Quon
         {% endblock %}


{% block body %}
    <main>
        <section class="slider-area ">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height d-flex align-items-center">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-6 col-lg-7 col-md-12">
                                <div class="hero__caption">
                                    <h1 data-animation="fadeInLeft" data-delay="0.2s">Online learning<br> platform</h1>
                                    <p data-animation="fadeInLeft" data-delay="0.4s">Build skills with courses, certificates, and degrees online from world-class universities and companies</p>

                                    <a href="../../../../login" class="btn hero-btn" data-animation="fadeInLeft" data-delay="0.7s">Login</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


    </main>
{% endblock%}

cloudapp/templates/scores.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
            O | Exam Solving
         {% endblock %}


{% block body %}
         <main>
        <!--? slider Area Start-->
        <section class="slider-area slider-area2">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height2">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-8 col-lg-11 col-md-12">
                                <div class="hero__caption hero__caption2">
                                    <h1 data-animation="bounceIn" data-delay="0.2s">Scores</h1>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--? Blog Area Start-->
        <section class="blog_area section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 mb-12 mb-lg-12">
                       <div class="section-top-border">
											<h3 class="mb-30">Scores</h3>
											<div class="progress-table-wrap">
												<div class="progress-table">
													<div class="table-head">
														<div class="serial">#</div>
														<div class="country">Name</div>
														<div class="visit">Score</div>
														<div class="percentage">Percentages</div>
													</div>

                                                    {% for ass in assignments %}

                                                        <div class="table-row">
                                                            <div class="serial"></div>
                                                            <div class="country">{{ ass.user_id }}</div>
                                                            <div class="visit">{{ ass.result }}</div>
                                                            <div class="percentage">
                                                                <div class="progress">
                                                                    <div class="progress-bar color-1" role="progressbar" style="width: {{ ass.result }}%" aria-valuenow="{{ ass.result }}" aria-valuemin="0" aria-valuemax="100"></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        
                                                    {% endfor %}
												</div>
											</div>
										</div>
                    </div>

                </div>
            </div>
        </section>
        <!-- Blog Area End -->
    </main>
{% endblock%}

cloudapp/templates/student.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
            O | Exam Solving
         {% endblock %}


{% block body %}
         <main>
        <!--? slider Area Start-->
        <section class="slider-area slider-area2">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height2">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-8 col-lg-11 col-md-12">
                                <div class="hero__caption hero__caption2">
                                    <h1 data-animation="bounceIn" data-delay="0.2s">Student System</h1>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--? Blog Area Start-->
        <section class="blog_area section-padding">
            <div class="container">
                <div class="row">
                {% if message %}



                     {% if warning %}
                          <div class="col-lg-12 mb-12 mb-lg-12">
                               <div class="alert alert-danger" role="alert">
                                     {{ message }}
                               </div>
                          </div>
                     {% else %}
                          <div class="col-lg-12 mb-12 mb-lg-12">
                                <div class="alert alert-success" role="alert">
                                      {{ message }}
                                </div>
                          </div>
                     {% endif %}


                {% endif %}
                    <div class="col-lg-12 mb-12 mb-lg-12">
                        <div class="blog_left_sidebar">
                            {% for exam in exams %}
                            <article class="blog_item">
                                
                                <div class="blog_details">
                                    <a class="d-inline-block" href="#">
                                        <h2 class="blog-head" style="color: #2d2d2d;">{{ exam.quiz_name}}</h2>
                                    </a>

                                        <h5 class="blog-head" style="color: #2d2d2d;">{{ exam.org_name}}</h5>

                                    <p>Dont Cheat | Lecture</p>
                                    <div class="d-inline-block">
                                        {% if exam.status %}
                                        <a href="{% url 'exam:detail' exam_id=exam.id %}" class="genric-btn info circle arrow">Join Exam<span class="lnr lnr-arrow-right"></span></a>
                                        {% else %}
                                        <a href="{% url 'exam:scores' exam_id=exam.id %}" class="genric-btn success circle arrow">See Your Grade<span class="lnr lnr-arrow-right"></span></a>
                                        <a href="{% url 'exam:answers' exam_id=exam.id  %}" class="genric-btn info circle arrow">See Correct Answers <span class="lnr lnr-arrow-right"></span></a>
                                        {% endif %}
                                    </div>
                                    </div>

                                    
                            </article>
                            {% endfor %}
                            <nav class="blog-pagination justify-content-center d-flex">
                                <ul class="pagination">
                                    <li class="page-item">
                                        <a href="#" class="page-link" aria-label="Previous">
                                            <i class="ti-angle-left"></i>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a href="#" class="page-link">1</a>
                                    </li>
                                    <li class="page-item active">
                                        <a href="#" class="page-link">2</a>
                                    </li>
                                    <li class="page-item">
                                        <a href="#" class="page-link" aria-label="Next">
                                            <i class="ti-angle-right"></i>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>

                </div>
            </div>
        </section>
        <!-- Blog Area End -->
    </main>
{% endblock%}